version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.13
    commands:
      - echo "Installing AWS CDK CLI..."
      - npm install -g aws-cdk
      - echo "Changing into cdk_backend directory"
      - cd Backend
      - echo "Installing dependencies..."
      - npm ci

  pre_build:
    commands:
      - echo "Building TypeScript sources..."
      - npm run build
      - echo "Bootstrapping CDK..."
      - cdk bootstrap --require-approval never
  build:
    commands:
      - |
        if [ "$ACTION" = "destroy" ]; then
          echo "Destroying CDK stack...";
          npx cdk destroy GeoReferencePipelineStack --force \
            --parameters BucketName="$BUCKET_NAME" \
            --parameters ErrorFolder="$ERROR_FOLDER" \
            --parameters AnalysisFolder="$ANALYSIS_FOLDER" \
            --parameters GithubToken="$GITHUB_TOKEN" \
            --parameters GithubRepoName="$GITHUB_REPO" \
            --parameters BedrockModelId="$BEDROCK_MODEL_ID" \
            --parameters BedrockRegion="$BEDROCK_REGION";
        else
          echo "Deploying CDK stack...";
          cdk deploy GeoReferencePipelineStack --require-approval never \
            --parameters BucketName="$BUCKET_NAME" \
            --parameters ErrorFolder="$ERROR_FOLDER" \
            --parameters AnalysisFolder="$ANALYSIS_FOLDER" \
            --parameters GithubToken="$GITHUB_TOKEN" \
            --parameters GithubRepoName="$GITHUB_REPO" \
            --parameters BedrockModelId="$BEDROCK_MODEL_ID" \
            --parameters BedrockRegion="$BEDROCK_REGION";
        fi
  post_build:
    commands:
      - echo "CDK $ACTION complete."
artifacts:
  files:
    - '**/*'
  base-directory: 'cdk.out'